
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tw_task_development


test:
  <<: *default
  database: tw_task_test


production:
  <<: *default
  database: tw_task_production
  username: tw_task
  password: <%= ENV['TW_TASK_DATABASE_PASSWORD'] %>
